/**
 * 漢字 / 漢字混じり語の英訳辞書（ベストエフォート用）。
 *
 * 形態素解析 (kuromoji 等) は ~3MB 級の辞書を持ち込むことになるので採用せず、
 * グルメアプリ実用上で目にする語だけ手書きで用意する。
 *
 * 適用順は「長いキー → 短いキー」（最長一致でまず置換、残った 1 字を最後に拾う）。
 * 漢字混じりでヒットしない部分は仮名 → romaji のフォールスルーに送る。
 *
 * 値は Title Case 寄りで揃える：固有名詞は "Ginza"、一般語は "ya" / "ten" など、
 * 文脈で繋がっても破綻しないように。
 */

/** 複合語・固有名詞（地名 / 駅名 / よくある屋号 / 食物名）。長さ降順で適用される。 */
export const KANJI_COMPOUNDS: Record<string, string> = {
  // ─── 大阪エリア・駅 ───
  '大阪府': 'Osaka',
  '大阪市': 'Osaka City',
  '大阪駅': 'Osaka Sta.',
  '大阪': 'Osaka',
  '梅田': 'Umeda',
  '北新地': 'Kitashinchi',
  '心斎橋': 'Shinsaibashi',
  '難波': 'Namba',
  '日本橋': 'Nipponbashi',
  '福島': 'Fukushima',
  '本町': 'Honmachi',
  '京橋': 'Kyobashi',
  '天王寺': 'Tennoji',
  '寺田町': 'Teradacho',
  '阿倍野': 'Abeno',
  '住吉': 'Sumiyoshi',
  '堺': 'Sakai',
  '中之島': 'Nakanoshima',
  '西梅田': 'Nishi-Umeda',
  '東梅田': 'Higashi-Umeda',
  '新大阪': 'Shin-Osaka',
  '弁天町': 'Bentencho',
  '玉造': 'Tamatsukuri',
  '森ノ宮': 'Morinomiya',
  '鶴橋': 'Tsuruhashi',
  '十三': 'Juso',
  '西中島': 'Nishi-Nakajima',
  '江坂': 'Esaka',
  '南森町': 'Minamimorimachi',
  '谷町': 'Tanimachi',
  '長堀': 'Nagahori',
  '堂島': 'Dojima',
  '曽根崎': 'Sonezaki',
  '茶屋町': 'Chayamachi',
  '裏なんば': 'Ura-Namba',
  '裏難波': 'Ura-Namba',
  '美章園': 'Bishoen',

  // ─── 東京エリア・駅 ───
  '渋谷': 'Shibuya',
  '新宿': 'Shinjuku',
  '原宿': 'Harajuku',
  '表参道': 'Omotesando',
  '青山': 'Aoyama',
  '六本木': 'Roppongi',
  '銀座': 'Ginza',
  '日比谷': 'Hibiya',
  '丸の内': 'Marunouchi',
  '有楽町': 'Yurakucho',
  '神田': 'Kanda',
  '秋葉原': 'Akihabara',
  '上野': 'Ueno',
  '浅草': 'Asakusa',
  '池袋': 'Ikebukuro',
  '恵比寿': 'Ebisu',
  '中目黒': 'Naka-Meguro',
  '目黒': 'Meguro',
  '代々木': 'Yoyogi',
  '高田馬場': 'Takadanobaba',
  '吉祥寺': 'Kichijoji',
  '下北沢': 'Shimokitazawa',
  '神楽坂': 'Kagurazaka',
  '麻布十番': 'Azabu-Juban',
  '広尾': 'Hiroo',
  '白金': 'Shirokane',
  '築地': 'Tsukiji',
  '豊洲': 'Toyosu',
  '東京都': 'Tokyo',
  '東京駅': 'Tokyo Sta.',
  '東京': 'Tokyo',
  '渋谷区': 'Shibuya',
  '新宿区': 'Shinjuku',
  '世田谷区': 'Setagaya',
  '港区': 'Minato',
  '中央区': 'Chuo',
  '台東区': 'Taito',
  '千代田区': 'Chiyoda',
  '北区': 'Kita',
  '東区': 'Higashi',
  '南区': 'Minami',
  '西区': 'Nishi',

  // ─── 京都エリア ───
  '京都': 'Kyoto',
  '祇園': 'Gion',
  '河原町': 'Kawaramachi',
  '四条': 'Shijo',
  '三条': 'Sanjo',
  '烏丸': 'Karasuma',
  '嵐山': 'Arashiyama',
  '伏見': 'Fushimi',
  '宇治': 'Uji',

  // ─── 神戸 / 兵庫 ───
  '神戸': 'Kobe',
  '三宮': 'Sannomiya',
  '元町': 'Motomachi',
  '芦屋': 'Ashiya',
  '西宮': 'Nishinomiya',
  '尼崎': 'Amagasaki',
  '宝塚': 'Takarazuka',

  // ─── その他主要都市 ───
  '横浜': 'Yokohama',
  '名古屋': 'Nagoya',
  '札幌': 'Sapporo',
  '仙台': 'Sendai',
  '福岡': 'Fukuoka',
  '博多': 'Hakata',
  '広島': 'Hiroshima',
  '金沢': 'Kanazawa',
  '那覇': 'Naha',
  '沖縄': 'Okinawa',

  // ─── 駅 / 周辺 ───
  '駅前': 'Eki-mae',
  '駅店': 'Sta. Branch',
  '駅西口': 'Sta. West Exit',
  '駅東口': 'Sta. East Exit',
  '駅南口': 'Sta. South Exit',
  '駅北口': 'Sta. North Exit',
  '駅': 'Sta.',
  '本店': 'Main Branch',
  '支店': 'Branch',

  // ─── 飲食ジャンル / 屋号でよく出る語（複合） ───
  '立ち呑み': 'Standing Bar',
  '立ち飲み': 'Standing Bar',
  '創作和食': 'Modern Japanese',
  '創作料理': 'Creative Cuisine',
  '居酒屋': 'Izakaya',
  '寿司屋': 'Sushiya',
  '蕎麦屋': 'Sobaya',
  '蕎麦': 'Soba',
  '焼肉': 'Yakiniku',
  '焼鳥': 'Yakitori',
  '焼き鳥': 'Yakitori',
  '中華そば': 'Chuka Soba',
  '町中華': 'Local Chinese',
  '中華': 'Chinese',
  '韓国料理': 'Korean',
  '韓国': 'Korean',
  '和食': 'Japanese',
  '洋食': 'Yoshoku',
  '定食': 'Set Meal',
  '食堂': 'Diner',
  '食べ歩き': 'Tabearuki',
  '食パン': 'Shokupan',
  '海鮮': 'Seafood',
  '魚介': 'Seafood',
  '海鮮丼': 'Seafood Donburi',
  '海老': 'Ebi',
  '炉端焼き': 'Robata',
  '炉端': 'Robata',
  '鉄板焼き': 'Teppanyaki',
  '鉄板': 'Teppan',
  '串揚げ': 'Kushiage',
  '串カツ': 'Kushikatsu',
  '天ぷら': 'Tempura',
  'とんかつ': 'Tonkatsu',
  '豚カツ': 'Tonkatsu',
  '豚しゃぶ': 'Buta-shabu',
  'しゃぶしゃぶ': 'Shabu-shabu',
  'すき焼き': 'Sukiyaki',
  '寿司': 'Sushi',
  '鮨': 'Sushi',
  'ラーメン': 'Ramen', // 早期マッチで残カナを救う
  'うどん': 'Udon',
  '深夜営業': 'Late Night',
  '飲み会': 'Drinks',
  '飲み': 'Drinks',
  '晩ご飯': 'Dinner',
  '昼ご飯': 'Lunch',
  '朝ご飯': 'Breakfast',
  '記念日': 'Anniversary',
  '夜景': 'Night View',
  '時間': 'h',

  // ─── 屋号・人名でよく出る固有 ───
  '銀座屋': 'Ginzaya',
  '次郎': 'Jiro',
  '太郎': 'Taro',
  '花子': 'Hanako',
  '横綱': 'Yokozuna',
  '燈火': 'Tomoshibi',
  '灯火': 'Tomoshibi',
  '満腹': 'Manpuku',
  '一番': 'Ichiban',

  // ─── 接尾語（屋号系） ───
  '本舗': 'Honpo',
  '商店': 'Shoten',
  '亭': 'Tei',
  '庵': 'An',
  '堂': 'Do',
  '軒': 'Ken',
  '館': 'Kan',
  '苑': 'En',
  '園': 'En',
  '屋': 'Ya',
  '店': 'Ten',
  '家': 'Ya',
};

/**
 * 単漢字フォールバック（compounds でも辞書未登録 kana でも拾えなかった残骸を救う）。
 * 音読み中心。固有名詞では「読み」が破綻しやすいが「無理やり」OK 方針なので妥協。
 */
export const KANJI_SINGLE: Record<string, string> = {
  // 食物
  '麺': 'men', '丼': 'don', '飯': 'han', '酒': 'sake', '茶': 'cha',
  '肉': 'niku', '魚': 'sakana', '鳥': 'tori', '鶏': 'tori', '豚': 'buta',
  '牛': 'gyu', '海': 'umi', '山': 'yama', '川': 'kawa', '田': 'ta',
  '米': 'kome', '野': 'no', '菜': 'sai', '油': 'abura', '塩': 'shio',
  '味': 'aji', '香': 'ka', '辛': 'kara', '甘': 'ama', '苦': 'niga',
  '酸': 'san', '熱': 'atsu', '冷': 'rei',
  // 数字
  '一': 'ichi', '二': 'ni', '三': 'san', '四': 'shi', '五': 'go',
  '六': 'roku', '七': 'shichi', '八': 'hachi', '九': 'kyu', '十': 'ju',
  '百': 'hyaku', '千': 'sen', '万': 'man',
  // 方角
  '東': 'higashi', '西': 'nishi', '南': 'minami', '北': 'kita',
  '中': 'naka', '上': 'ue', '下': 'shita', '内': 'uchi', '外': 'soto',
  // よく見る漢字
  '町': 'machi', '村': 'mura', '区': 'ku', '市': 'shi', '都': 'to',
  '府': 'fu', '県': 'ken', '島': 'shima', '丘': 'oka',
  '橋': 'bashi', '坂': 'saka', '通': 'dori', '路': 'ji',
  '日': 'hi', '月': 'tsuki', '年': 'nen', '時': 'ji', '分': 'fun',
  '人': 'jin', '大': 'oo', '小': 'ko', '長': 'naga', '短': 'mijika',
  '新': 'shin', '古': 'furu', '高': 'taka', '低': 'hiku',
  '銀': 'gin', '金': 'kin', '木': 'ki', '林': 'hayashi', '森': 'mori',
  '花': 'hana', '春': 'haru', '夏': 'natsu', '秋': 'aki', '冬': 'fuyu',
  '光': 'hikari', '心': 'kokoro', '愛': 'ai', '夢': 'yume',
  '空': 'sora', '雲': 'kumo', '雨': 'ame', '雪': 'yuki', '風': 'kaze',
  '火': 'hi', '水': 'mizu', '土': 'do',
  '本': 'hon', '末': 'matsu',
  '呑': 'nomi', '飲': 'nomi', '食': 'shoku',
  '玉': 'tama', '石': 'ishi',
  '生': 'nama', '熟': 'juku',
  '夜': 'yoru', '朝': 'asa', '昼': 'hiru', '晩': 'ban',
  '前': 'mae', '後': 'ato', '左': 'hidari', '右': 'migi',
  '寺': 'tera', '神': 'kami', '宮': 'miya',
  '創': 'so', '作': 'saku', '料': 'ryo', '理': 'ri',
  '商': 'sho', '業': 'gyo', '会': 'kai', '社': 'sha',
  '駅': 'eki',
};

/** longest-match のためにキー長で降順ソートされたエントリーを 1 度だけ作る。 */
export const COMPOUND_KEYS_DESC: string[] = Object.keys(KANJI_COMPOUNDS).sort((a, b) => b.length - a.length);
